name = "glats"
version = "0.9.1"
description = "A NATS client for Gleam."

licences = ["MIT"]
repository = { type = "github", user = "arnarg", repo = "glats" }
gleam = ">= 1.4.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gnat = "~> 1.11"
gleam_erlang = "~> 1.3.0"
gleam_otp = "~> 1.1"
gleam_json = "~> 3.0"
gleam_crypto = "~> 1.5"

[dev-dependencies]
gleeunit = "~> 1.0"
